### ISSUE TITLE
[Bug] LILYGO T-Dongle-S3 fails to flash via web tool, requires manual build flags

### ISSUE THREAD

**Issue by pyotty** [BitMaker-hub/NerdMiner_v2#665]
Problem Description
I am experiencing an issue when trying to flash a NerdMiner firmware on a LILYGO T-Dongle-S3 board using the official web flasher. The process seems to complete, but the device enters a boot loop and the screen remains blank. This occurs with multiple firmware versions.

Hardware and Firmware Versions
- Board: LILYGO T-Dongle-S3 (ESP32-S3 chip, ST7735 LCD)
- Web Flasher: https://flasher.bitronics.store/
- Firmware Tested: NerdminerV2-S3-DONGLE (versions 1.6.3, 1.7.0, 1.7.1, 1.8.0)

Steps to Reproduce
- Connect the LILYGO T-Dongle-S3 to the PC.
- Navigate to https://flasher.bitronics.store/.
- Select the NerdminerV2-S3-DONGLE board from the dropdown.
- Flash the device.

Expected Behavior
The firmware should be uploaded successfully, and the device should start the mining process.

Actual Behavior
After the flashing process, the device enters a continuous reset loop (boot loop) and the LCD screen remains black. The device becomes unusable.

Supporting Images
 LILYGO T-Dongle-S3 board
<img width="456" height="434" alt="Image" src="https://github.com/user-attachments/assets/e69e0bf2-cb17-45ba-ab13-714bad9c3067" />

Working Solution (Manual Build)
I was able to get a working version by manually compiling the firmware. The issue appears to be related to the pinout configuration for the display. The original firmware I started with was 1.6.3.

- I downloaded the source code from https://github.com/matlen67/NerdMiner_V2_ESP32-ST7735.
- I edited the platformio.ini file under the [env:ESP32_ST7735] section.
- I added the following build_flags to explicitly define the ST7735 display pins:

Ini, TOML

build_flags =
    ...
    -DTFT_MOSI=3
    -DTFT_SCLK=5
    -DTFT_CS=4
    -DTFT_DC=2
    -DTFT_RST=1
After compiling and uploading with PlatformIO, the firmware works correctly.

Note: The solution works, but the firmware version is not the latest one.

LILYGO T-Dongle-S3 with working firmware
<img width="506" height="365" alt="Image" src="https://github.com/user-attachments/assets/a8c8f313-a8e4-4e03-8e4f-2b9c11335655" />

Is there a way to update your device to version 1.6.3 or newer via website?

**Comment by BitMaker-hub** [comment]
hi, sure, yes.
I personally don't have with me the dongle version, but if you was able to compile and see the screen with this settings should work after compiling a new prerelease. 

Can you do this changes on dev branch, test them and then make a PR please?

**Comment by BitMaker-hub** [comment]
I'll try to get a board and fix this

**Comment by pyotty** [comment]
I'll be away from home for a few weeks for work and in any case I received help from a friend and I wouldn't know how to repeat the whole process.

If you can find the same device that would be perfect.
Thank you

**Comment by BitMaker-hub** [comment]
If there is anybody with ths board and can try the new release, could help me

**Comment by MasterHD48** [comment]
The same problem. Tried to use T-DONGLE S3 with flasher(using NERDMINER_V2-S3-DONGLE) and it just don't work. Display is always black. Btw sometimes the logs contain information about the mining process, which is good. But without a working screen, it's difficult to monitor whether everything is working properly. Tried to use all versions(1.7.0, 1.6.3, 1.8.3)

**Comment by BitMaker-hub** [comment]
ok, guys I ordered a dongle so I'll be able to test soon

**Comment by roelfrenkema** [comment]
> * I downloaded the source code from https://github.com/matlen67/NerdMiner_V2_ESP32-ST7735.
> * I edited the platformio.ini file under the [env:ESP32_ST7735] section.
> * I added the following build_flags to explicitly define the ST7735 display pins:
> 
> Ini, TOML
> 
> build_flags = ... -DTFT_MOSI=3 -DTFT_SCLK=5 -DTFT_CS=4 -DTFT_DC=2 -DTFT_RST=1 After compiling and uploading with PlatformIO, the firmware works correctly.
> 
another step was needed

board = esp32-s3-devkitc-1

if you dont it will bailout with the message the board is no esp32 but an esp32-c

And though you get it running this way, the one button options dont work (SOLVED with adding build flag -D PIN_BUTTON_1=0) and you miss half of the display. Only the top half is shown and the more important info is on the bottom. So we need a screen write and probably more pin changes for the button.

OK that build flag seems to be the last neccesary change. Now I can see a clock and a decent hashrate of up 80.

So this is what you need.

1. Change the board to board = esp32-s3-devkitc-1
2. Chang buildflags: 
-DTFT_MOSI=3
-DTFT_SCLK=5
-DTFT_CS=4
-DTFT_DC=2
-DTFT_RST=1
3. Add build flag:  -D PIN_BUTTON_1=0
4. compile and upload
5. connect to the AP
6. set your browser to 192.168.4.1 and finish the configuration.
7. Feel free to use bc1qqkn335q088u0y2v9nje7dq7xqkrgc5mmcy7tmr to donate xxx

**Comment by 68xy** [comment]
what would i compile it with? arduino ide or platformio?

**Comment by hx6vsvht2d-dev** [comment]
Have you found a solution ? Same problem : black screen after flashing v1.8.3 
I had to manually reconfigure it using only version 1.6.3

**Comment by bigengdaddy-del** [comment]
Im still having this problem.  issue being that mine came with V.02, and the update didnt work, and the firmware update i tried just blanked it out. Tried deleting and adding everything back, and it still isn't working.

**Comment by n2hyo** [comment]
I am having same issue.

**Comment by tanqtuol** [comment]
same problem

**Comment by tanqtuol** [comment]
https://bitmaker-hub.github.io/diyflasher/

I used this NMV2 1.6.3 on LILYGO S3 Dongle, it is working

**Comment by ShadsDen** [comment]
> https://bitmaker-hub.github.io/diyflasher/
> 
> I used this NMV2 1.6.3 on LILYGO S3 Dongle, it is working

Nope it doesn't work. Just see the Wifi config and nothing else.

**Comment by rodrigoveroli** [comment]
I did the latest website update and now the dongle is stuck in an infinite loop. I reverted to the first version on the old website and it only shows the Wi-Fi message.

**Comment by Lunas2525** [comment]
So heres the deal this doesnt update via the new website it leaves one with no screen as per the above issue the old site can flash 1.6.3 to it and gets it back operational. steps to do so hold button as you plug in then erase flash then refresh the page and flash 1.6.3 it should end up asking you to Use wifi for setup connect to the nerd miner ap and setup as per normal.

i am going to try using the internal update option.

**Comment by pyotty** [comment]
SOLVED - Root Cause Found
After extensive debugging, the issue is a single line in platformio.ini.
The [env:NerdminerV2-S3-DONGLE] block is missing:

-DTFT_BACKLIGHT_ON=LOW

The T-Dongle-S3 backlight is active LOW, not HIGH. 
The current firmware has no TFT_BACKLIGHT_ON definition for this environment, which defaults to HIGH in TFT_eSPI , causing the display to stay black (backlight always off).

Fix: add to platformio.ini under [env:NerdminerV2-S3-DONGLE]:
-DTFT_BACKLIGHT_ON=LOW

Also needed (missing from current build_flags):
-DUSER_SETUP_LOADED=1
-DST7735_DRIVER=1
-DTFT_WIDTH=128
-DTFT_HEIGHT=160
-DTFT_MOSI=3
-DTFT_SCLK=5
-DTFT_CS=4
-DTFT_DC=2
-DTFT_RST=1
-DTFT_BL=38
-DSPI_FREQUENCY=27000000
-DSPI_READ_FREQUENCY=20000000

Tested on firmware v1.8.3 — mining works and display scrolls correctly.


Additional bugs found during debugging:
1. Button not working — remove -DBOARD_HAS_PSRAM from build flags
The BOARD_HAS_PSRAM flag interferes with GPIO0 (the only button on T-Dongle-S3), making it unresponsive. Removing it fixes the button completely.
2. Shares rejected by pool — extranonce2 padding bug in utils.cpp
getNextExtranonce2() and getRandomExtranonce2() use a broken format string pattern:

char format[] = "%00x";
sprintf(&format[1], "%02dx", extranonce2_size * 2);

When extranonce2_size = 8, this produces "%16x" (space-padded) instead of "%016x" (zero-padded), causing the pool to reject all shares with "Difficulty too low".
Fix in src/utils.cpp — replace both occurrences with:

char format[12];
snprintf(format, sizeof(format), "%%0%dx", extranonce2_size * 2);
sprintf(extranonce2, format, extranonce2_number);

Also change strtoul(extranonce2, NULL, 10) to strtoul(extranonce2, NULL, 16) (base 16 instead of base 10).

**Comment by ffrediani** [comment]
I have the same issue with Lilygo S3 Dongle when using version 1.8.3 up to 1.7.0. It only worked with version 1.6.3

@pyotty can you make the binary file available for this fixed build ?
Also can you make a PR so this can get fixed definitely ?

@BitMaker-hub were you able to reproduce it with the unit your purchased and confirm the fix ? Perhaps you can push this fix as well.

**Comment by pyotty** [comment]
Hi,

I can confirm the fix works on firmware 1.8.3. There are actually 3 separate bugs to fix:

## 1. `platformio.ini` — display black screen

Remove `-DBOARD_HAS_PSRAM` and update `[env:NerdminerV2-S3-DONGLE]` build_flags:

```ini
-DTFT_BACKLIGHT_ON=LOW
-DUSER_SETUP_LOADED=1
-DST7735_DRIVER=1
-DTFT_WIDTH=128
-DTFT_HEIGHT=160
-DTFT_MOSI=3
-DTFT_SCLK=5
-DTFT_CS=4
-DTFT_DC=2
-DTFT_RST=1
-DTFT_BL=38
-DSPI_FREQUENCY=27000000
-DSPI_READ_FREQUENCY=20000000
```

## 2. `src/utils.cpp` — pool rejects all shares

extranonce2 is space-padded instead of zero-padded, causing `Difficulty too low` on all shares.

Replace both occurrences of this pattern (in `getNextExtranonce2` and `getRandomExtranonce2`):

```cpp
char format[] = "%00x";
sprintf(&format[1], "%02dx", extranonce2_size * 2);
sprintf(extranonce2, format, extranonce2_number);
```

With:

```cpp
char format[12];
snprintf(format, sizeof(format), "%%0%dx", extranonce2_size * 2);
sprintf(extranonce2, format, extranonce2_number);
```

Also change:
```cpp
strtoul(extranonce2, NULL, 10)
```
to:
```cpp
strtoul(extranonce2, NULL, 16)
```

## 3. `src/drivers/displays/dongleDisplayDriver.cpp` — wrong image file

Change:
```cpp
#include "media/images_240_135.h"
```
to:
```cpp
#include "media/images_160_80.h"
```
And set `WIDTH=160`, `HEIGHT=80`.

---

I don't have a binary available right now. I will try to open a PR when I have time.
@BitMaker-hub please consider pushing these fixes directly.

**Comment by ffrediani** [comment]
@pyotty Thanks. Awaiting you to open a PR then

**Comment by ffrediani** [comment]
I managed build it myself and get it working, however I had to do add 2 extra build_flags on platformio.ini otherwise it wouldn't build.

```
-DLOAD_GFXFF=1
-DSMOOTH_FONT=1
```
The hashrate went from ~75kH/s to around 245kH/s from the version 1.7.0 that I was using previously.

Despite it worked as expected the background on display is now white instead of darker as the previous versions. Does anyone know to invert it back reduce luminosity a bit ?

**Comment by ffrediani** [comment]
@pyotty can you submit a PR as mentioned ?

**Comment by necklickhia** [comment]
Is there a way non-developers can use (people who don't know how to compile a new version)?
